export * from "./comment.model";
export * from "./district.model";
export * from "./location.model";
export * from "./news.model";
export * from "./polygon.model";
export * from "./province.model";
export * from "./real-estate.model";
export * from "./user.model";
export * from "./ward.model";