import "./globals.css";

import { Be_Vietnam_Pro } from "next/font/google";
import { GlobalProvider } from "@/provider";
import type { Metadata } from "next";

const be_vietnam_pro = Be_Vietnam_Pro({
  weight: "500",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={be_vietnam_pro.className}
    >
      <body className={`bg-zinc-50 dark:bg-black antialiased`}>
        <GlobalProvider>
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
